/**
 * AUTO-GENERATED by scripts/import-walls.py — DO NOT EDIT
 * Source: walls.png (64x128, 4x4 grid)
 * Bitmask: N=1, E=2, S=4, W=8
 */
import type { SpriteData } from '../types'

const _ = '' // transparent

/** Wall sprite bitmask=0 (0b0000) */
const WALL_0: SpriteData = [
  ['#302a28','#302a28','#302a28','#302a28','#302a28','#302a28','#302a28','#302a28'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
]

/** Wall sprite bitmask=1 (0b0001) */
const WALL_1: SpriteData = [
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
]

/** Wall sprite bitmask=2 (0b0010) */
const WALL_2: SpriteData = [
  ['#302a28','#302a28','#302a28','#302a28','#302a28','#302a28','#302a28','#302a28'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
]

/** Wall sprite bitmask=3 (0b0011) */
const WALL_3: SpriteData = [
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
]

/** Wall sprite bitmask=4 (0b0100) */
const WALL_4: SpriteData = [
  ['#302a28','#302a28','#302a28','#302a28','#302a28','#302a28','#302a28','#302a28'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
]

/** Wall sprite bitmask=5 (0b0101) */
const WALL_5: SpriteData = [
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
]

/** Wall sprite bitmask=6 (0b0110) */
const WALL_6: SpriteData = [
  ['#302a28','#302a28','#302a28','#302a28','#302a28','#302a28','#302a28','#302a28'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
]

/** Wall sprite bitmask=7 (0b0111) */
const WALL_7: SpriteData = [
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
]

/** Wall sprite bitmask=8 (0b1000) */
const WALL_8: SpriteData = [
  ['#302a28','#302a28','#302a28','#302a28','#302a28','#302a28','#302a28','#302a28'],
  ['#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
]

/** Wall sprite bitmask=9 (0b1001) */
const WALL_9: SpriteData = [
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
]

/** Wall sprite bitmask=10 (0b1010) */
const WALL_10: SpriteData = [
  ['#302a28','#302a28','#302a28','#302a28','#302a28','#302a28','#302a28','#302a28'],
  ['#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
]

/** Wall sprite bitmask=11 (0b1011) */
const WALL_11: SpriteData = [
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
]

/** Wall sprite bitmask=12 (0b1100) */
const WALL_12: SpriteData = [
  ['#302a28','#302a28','#302a28','#302a28','#302a28','#302a28','#302a28','#302a28'],
  ['#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
]

/** Wall sprite bitmask=13 (0b1101) */
const WALL_13: SpriteData = [
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
]

/** Wall sprite bitmask=14 (0b1110) */
const WALL_14: SpriteData = [
  ['#302a28','#302a28','#302a28','#302a28','#302a28','#302a28','#302a28','#302a28'],
  ['#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
  ['#302a28','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'],
]

/** Wall sprite bitmask=15 (0b1111) */
const WALL_15: SpriteData = [
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
  ['#302a28','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9','#cac6b9'],
]

/** All 16 wall sprites indexed by bitmask (0-15) */
export const WALL_SPRITES: SpriteData[] = [
  WALL_0,
  WALL_1,
  WALL_2,
  WALL_3,
  WALL_4,
  WALL_5,
  WALL_6,
  WALL_7,
  WALL_8,
  WALL_9,
  WALL_10,
  WALL_11,
  WALL_12,
  WALL_13,
  WALL_14,
  WALL_15,
]
