#!/usr/bin/env python3
"""
Import character sprite sheets (char_0.png ~ char_N.png) into TypeScript.

Each PNG is 112×96 (7 frames × 16px wide, 3 directions × 32px tall).
Grid layout:
  - Columns (7): walk1, walk2, walk3, type1, type2, read1, read2
  - Rows (3): down, up, right

Outputs: dashboard/src/lib/pixel-office/sprites/characterSprites.ts
Each character → LoadedCharacterData { down: SpriteData[7], up: SpriteData[7], right: SpriteData[7] }
"""

import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("pip install Pillow first", file=sys.stderr)
    sys.exit(1)

CHARS_DIR = Path(__file__).parent.parent / "dashboard/public/assets/pixel-office/characters"
OUTPUT = Path(__file__).parent.parent / "dashboard/src/lib/pixel-office/sprites/characterSprites.ts"

FRAME_W = 16
FRAME_H = 32
FRAMES_PER_ROW = 7
DIRECTIONS = 3  # down, up, right


def rgb_to_hex(r: int, g: int, b: int) -> str:
    return f"#{r:02x}{g:02x}{b:02x}"


def extract_frame(img: Image.Image, col: int, row: int) -> list[list[str]]:
    """Extract a single 16×32 frame."""
    x0 = col * FRAME_W
    y0 = row * FRAME_H
    pixels = img.load()
    frame: list[list[str]] = []
    for y in range(y0, y0 + FRAME_H):
        row_data: list[str] = []
        for x in range(x0, x0 + FRAME_W):
            pixel = pixels[x, y]
            if len(pixel) == 4:
                r, g, b, a = pixel
                if a < 128:
                    row_data.append("")
                else:
                    row_data.append(rgb_to_hex(r, g, b))
            else:
                r, g, b = pixel
                row_data.append(rgb_to_hex(r, g, b))
        frame.append(row_data)
    return frame


def sprite_to_ts(sprite: list[list[str]], indent: str = "    ") -> str:
    lines = []
    for row in sprite:
        cells = []
        for c in row:
            cells.append("_" if c == "" else f"'{c}'")
        lines.append(f"{indent}[{','.join(cells)}],")
    return "\n".join(lines)


def main():
    # Find all char_*.png files, sorted by number
    char_files = sorted(CHARS_DIR.glob("char_*.png"), key=lambda p: int(p.stem.split("_")[1]))

    if not char_files:
        print(f"No char_*.png files found in {CHARS_DIR}", file=sys.stderr)
        sys.exit(1)

    # Filter to standard size only (112×96), skip upscaled versions
    standard_files = []
    for f in char_files:
        img = Image.open(f)
        if img.size == (112, 96):
            standard_files.append(f)
        else:
            print(f"  Skipping {f.name}: {img.size[0]}x{img.size[1]} (not 112x96)")

    print(f"Found {len(standard_files)} standard character sprite sheets")

    ts_lines = [
        "/**",
        " * AUTO-GENERATED by scripts/import-characters.py — DO NOT EDIT",
        f" * Source: {len(standard_files)} character sprite sheets (112x96, 7 frames × 3 directions)",
        " */",
        "import type { SpriteData } from '../types'",
        "import type { LoadedCharacterData } from './spriteData'",
        "",
        "const _ = '' // transparent",
        "",
    ]

    char_names = []
    for f in standard_files:
        img = Image.open(f)
        if img.mode != "RGBA":
            img = img.convert("RGBA")

        char_idx = int(f.stem.split("_")[1])
        char_name = f"CHAR_{char_idx}"
        char_names.append(char_name)
        print(f"  Processing {f.name}...")

        dir_names = ["down", "up", "right"]

        ts_lines.append(f"/** Character {char_idx} from {f.name} */")
        ts_lines.append(f"const {char_name}: LoadedCharacterData = {{")

        for dir_idx, dir_name in enumerate(dir_names):
            ts_lines.append(f"  {dir_name}: [")
            for frame_idx in range(FRAMES_PER_ROW):
                frame = extract_frame(img, frame_idx, dir_idx)
                ts_lines.append(f"    [  // frame {frame_idx}")
                ts_lines.append(sprite_to_ts(frame))
                ts_lines.append("    ],")
            ts_lines.append("  ],")
        ts_lines.append("}")
        ts_lines.append("")

    ts_lines.append("/** All character sprites for setCharacterTemplates() */")
    ts_lines.append(f"export const CHARACTER_SPRITES: LoadedCharacterData[] = [")
    for name in char_names:
        ts_lines.append(f"  {name},")
    ts_lines.append("]")
    ts_lines.append("")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(ts_lines))
    print(f"Written {OUTPUT} ({len(char_names)} characters)")


if __name__ == "__main__":
    main()
