#!/usr/bin/env python3
"""
Import walls.png (64x128, 4x4 grid of 16x32 sprites) into TypeScript SpriteData.

Bitmask convention: N=1, E=2, S=4, W=8.
Grid layout (row-major, left-to-right, top-to-bottom) maps to bitmask 0-15.

Output: dashboard/src/lib/pixel-office/sprites/wallSprites.ts
"""

import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("pip install Pillow first", file=sys.stderr)
    sys.exit(1)

WALLS_PNG = Path(__file__).parent.parent / "dashboard/public/assets/pixel-office/walls.png"
OUTPUT = Path(__file__).parent.parent / "dashboard/src/lib/pixel-office/sprites/wallSprites.ts"

SPRITE_W = 16
SPRITE_H = 32
GRID_COLS = 4
GRID_ROWS = 4


def rgb_to_hex(r: int, g: int, b: int) -> str:
    return f"#{r:02x}{g:02x}{b:02x}"


def extract_sprite(img: Image.Image, col: int, row: int) -> list[list[str]]:
    """Extract a single sprite from the grid."""
    x0 = col * SPRITE_W
    y0 = row * SPRITE_H
    pixels = img.load()
    sprite: list[list[str]] = []
    for y in range(y0, y0 + SPRITE_H):
        row_data: list[str] = []
        for x in range(x0, x0 + SPRITE_W):
            pixel = pixels[x, y]
            # Handle RGBA or RGB
            if len(pixel) == 4:
                r, g, b, a = pixel
                if a < 128:
                    row_data.append("")
                else:
                    row_data.append(rgb_to_hex(r, g, b))
            else:
                r, g, b = pixel
                row_data.append(rgb_to_hex(r, g, b))
        sprite.append(row_data)
    return sprite


def sprite_to_ts(sprite: list[list[str]], indent: str = "  ") -> str:
    """Convert sprite to TypeScript SpriteData literal."""
    lines = []
    for row in sprite:
        cells = []
        for c in row:
            if c == "":
                cells.append("_")
            else:
                cells.append(f"'{c}'")
        lines.append(f"{indent}[{','.join(cells)}],")
    return "\n".join(lines)


def main():
    img = Image.open(WALLS_PNG)
    if img.mode not in ("RGB", "RGBA"):
        img = img.convert("RGBA")

    print(f"Loaded {WALLS_PNG}: {img.size[0]}x{img.size[1]} {img.mode}")

    sprites: list[list[list[str]]] = []
    for row in range(GRID_ROWS):
        for col in range(GRID_COLS):
            sprite = extract_sprite(img, col, row)
            sprites.append(sprite)

    assert len(sprites) == 16, f"Expected 16 sprites, got {len(sprites)}"

    # Generate TypeScript
    ts_lines = [
        "/**",
        " * AUTO-GENERATED by scripts/import-walls.py — DO NOT EDIT",
        f" * Source: walls.png ({img.size[0]}x{img.size[1]}, {GRID_COLS}x{GRID_ROWS} grid)",
        " * Bitmask: N=1, E=2, S=4, W=8",
        " */",
        "import type { SpriteData } from '../types'",
        "",
        "const _ = '' // transparent",
        "",
    ]

    for i, sprite in enumerate(sprites):
        ts_lines.append(f"/** Wall sprite bitmask={i} (0b{i:04b}) */")
        ts_lines.append(f"const WALL_{i}: SpriteData = [")
        ts_lines.append(sprite_to_ts(sprite))
        ts_lines.append("]")
        ts_lines.append("")

    ts_lines.append("/** All 16 wall sprites indexed by bitmask (0-15) */")
    ts_lines.append("export const WALL_SPRITES: SpriteData[] = [")
    for i in range(16):
        ts_lines.append(f"  WALL_{i},")
    ts_lines.append("]")
    ts_lines.append("")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(ts_lines))
    print(f"Written {OUTPUT} ({len(sprites)} sprites)")


if __name__ == "__main__":
    main()
